version: "3.7"

services:
  mongo-db:
    image: mongo
    container_name: "mongo-db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=mongoTutor
      - MONGO_INITDB_USERNAME=codewizz
      - MONGO_INITDB_PASSWORD=eve555%%
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./mongo-volume:/data/db


